### ISSUE TITLE
mtl and transformers relationship

### ISSUE THREAD

**Issue by Bodigrim** [JeanHuguesdeRaigniac/effects-landscape#1]
https://github.com/JeanHuguesdeRaigniac/effects-landscape/blob/e44aea11053ac4db85b862fab027d3777d35e232/README.md?plain=1#L21

This is a bit incorrect: `transformers` was not a challenger. It's that `mtl-1` was split into `transformers` (Haskell98 compliant) and `mtl-2` (with FunDeps and other GHC extensions).

**Comment by JeanHuguesdeRaigniac** [comment]
Thank you.
